version: '3.3'

services:

  backend:
    build: ./backend/
    env_file: .env
    command: > 
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers"

  bot:
    depends_on:
      - backend
    build: ./bot/
    env_file: .env
    command: > 
      sh -c "python main.py"

  nginx:
    depends_on:
      - backend
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80